"""Add descriptions to slaps users tracks.

Revision ID: 26a4d837a81f
Revises: 
Create Date: 2023-07-21 13:25:17.133931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26a4d837a81f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slaps_user_upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slaps_user_upload', schema=None) as batch_op:
        batch_op.drop_column('description')